### ISSUE TITLE
Bug: Provider crash when modifying policy assignments

### ISSUE THREAD

**Issue by JWilkinsonMB** [Azure/terraform-provider-alz#148]
It looks like attempting to modify policy assignments at the second level causes a crash, e.g.:
```
policy_assignments_to_modify = {
    corp = {
      policy_assignments = {
        Deny-Public-IP-On-NIC = {
          enforcement_mode = "DoNotEnforce"
        }
      }
    }
  }
```
Results in:
```
module.alz.module.alz_global.data.alz_architecture.this: Still reading... [50s elapsed]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-alz_v0.15.2.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x1394ac5]

goroutine 171 [running]:
github.com/Azure/alzlib/deployment.(*HierarchyManagementGroup).ModifyPolicyAssignment(0x0, {0xc0005d3a28, 0x15}, 0x0, 0xc0010d63f0, {0x0, 0x0, 0x0}, 0x0, {0x0, ...}, ...)
        github.com/Azure/alzlib@v0.21.7/deployment/managementgroup.go:353 +0x65
github.com/Azure/terraform-provider-alz/internal/provider.modifyPolicyAssignments({_, _}, _, {{0x0, {0x0, 0x0}}, {0x2, {0xc00061d7c0, 0xb}}, {{0x0, ...}, ...}, ...}, ...)
        github.com/Azure/terraform-provider-alz/internal/provider/architecture_data_source.go:178 +0x82b
github.com/Azure/terraform-provider-alz/internal/provider.(*architectureDataSource).Read(0xc0009a2f88, {0x1ba4508, 0xc0007bc750}, {{{{0x1bab390, 0xc000b39bf0}, {0x18aac00, 0xc000ab3440}}, {0x1bae340, 0xc00063f180}}, {{{0x0, ...}, ...}, ...}, ...}, ...)
        github.com/Azure/terraform-provider-alz/internal/provider/architecture_data_source.go:108 +0x7f8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc00021a1e0, {0x1ba4508, 0xc0007bc750}, 0xc0006b5280, 0xc000b336d8)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_readdatasource.go:103 +0x751
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc00021a1e0, {0x1ba4508?, 0xc0007bc660?}, 0xc0007bc600)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_readdatasource.go:55 +0x389
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc00023a3c0, {0x1ba4508?, 0xc0008d7860?}, 0xc00011cb40)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:688 +0x26d
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x19e1300, 0xc00023a3c0}, {0x1ba4508, 0xc0008d7860}, 0xc00042a700, 0x0)      
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:572 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000191000, {0x1ba4508, 0xc0008d7740}, {0x1bacc00, 0xc0003f6000}, 0xc00075b440, 0xc000319110, 0x22755a0, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xe11
google.golang.org/grpc.(*Server).handleStream(0xc000191000, {0x1bacc00, 0xc0003f6000}, 0xc00075b440)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 36
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x125

Error: The terraform-provider-alz_v0.15.2.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

However when modifying a policy one level higher, there's no issue.
```
policy_assignments_to_modify = {
    landing_zones = {
      policy_assignments = {
        Enable-DDoS-VNET = {
          enforcement_mode = "DoNotEnforce"
        }
      }
    }
  }
```

**Comment by matt-FFFFFF** [comment]
Thanks @JWilkinsonMB I'll take a look

**Comment by matt-FFFFFF** [comment]
Hi, I could not repro this - I tried with the following config:

```terraform
provider "alz" {
	library_references = [
		{
			path = "platform/alz"
			ref  = "2024.10.0"
		}
	]
}

data "azapi_client_config" "current" {}

data "alz_architecture" "test" {
	name                     = "alz"
	root_management_group_id = data.azapi_client_config.current.tenant_id
	location                 = "swedencentral"
	policy_assignments_to_modify = {
		corp = {
			policy_assignments = {
				Deny-Public-IP-On-NIC = {
					enforcement_mode = "DoNotEnforce"
				}
			}
		}
	}
}
```

Please can you provide more of your config so I can try and troubleshoot? Thanks

**Comment by JWilkinsonMB** [comment]
Hi @matt-FFFFFF thanks for checking. Does this work for you as an MRE?

```HCL
provider "alz" {
  library_references = [
    {
      path = "platform/alz"
      ref  = "2024.10.0"
    }
  ]
}

data "azapi_client_config" "current" {}

data "alz_architecture" "test" {
  name                     = "alz"
  root_management_group_id = data.azapi_client_config.current.tenant_id
  location                 = "swedencentral"
  policy_assignments_to_modify = {
    root = {
      policy_assignments = {
        Deploy-MDEndpoints = {
          enforcement_mode = "DoNotEnforce"
        }
      }
    }
  }
}
```

It looks like it doesn't make a difference what the hierarchy level is, so I started looking at the archetype overrides, which may still be related. 

Up until I hit the error, all of the policies I was modifying were ones that I'd added to the archetype via an override. What triggered the error initially was trying to modify an assignment where it was defined on the base archetype, not the override.  

I started chasing my tail trying to confirm that, but it led to the above, where a policy modified on the root triggers the crash.

**Comment by matt-FFFFFF** [comment]
Thanks for the additional info.

To confirm the repro steps are:

1. Create override archetype based on, say, root.

2. Add or remove some assignments.

3. Create custom architecture with the override archetype instead of the base

4. Modify a policy assignment that is part of the base archetype

Feel free to comment on this to set me on the right path!

**Comment by matt-FFFFFF** [comment]
> Hi [@matt-FFFFFF](https://github.com/matt-FFFFFF) thanks for checking. Does this work for you as an MRE?

Hi I can repro with this code - working on identifying the issue

**Comment by matt-FFFFFF** [comment]
Hi @JWilkinsonMB 

I have found the cause of the issue. In your repro steps the management group `root` does not exist in the architecture. The root MG in the default architecture is called `alzroot`.

Within the `modifyPolicyAssignments()` func we use a mathod call on the deployment to retrieve the `deployment.HierarchyManagementGroup`. the `ModifyPolicyAssignment()` method is then called to make the modifications.

https://github.com/Azure/terraform-provider-alz/blob/4eee62405ca9e299a50c54b697aff27763fc8e23/internal/provider/architecture_data_source.go#L178-L179

The alzlib method `ManagementGroup` is a simple function that returns a `nil` if the supplied name does not exist:

```go
// ManagementGroup returns the management group with the given name.
func (h *Hierarchy) ManagementGroup(name string) *HierarchyManagementGroup {
	h.mu.RLock()
	defer h.mu.RUnlock()
	if mg, ok := h.mgs[name]; ok {
		return mg
	}
	return nil
}
```

The provider does not check for a nil response and that is where the error occurs.

I will make the fix today and publish a new release.

**Comment by JWilkinsonMB** [comment]
Thanks! That explanation also pointed me to where I was going wrong originally and why I saw the crash when I did. When adding the new policy to modify I was using the archetype name rather than management group ID. Despite going over the config it didn't click as up until that point the management group IDs and archetype names were the same.
